In [16]:
!pip install pandas sqlalchemy sqlite3

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (1.4.46)
ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3

In [17]:
import pandas as pd

# Replace 'your_file.csv' with the path to your CSV file
df = pd.read_csv('/content/dataset.csv')

In [18]:
df['order_id'] = pd.to_numeric(df['order_id'], errors='coerce')
df.dropna(subset=['order_id'], inplace=True)
df['order_id'] = df['order_id'].astype(int)

In [19]:
df = df[df['product_id'] != 0]

In [20]:
df['amount'] = df['amount'].apply(lambda x: 1500 if x > 1500 else x)

In [21]:
df.dropna(subset=['status'], inplace=True)

In [22]:
df.drop_duplicates(inplace=True)

In [23]:
from sqlalchemy import create_engine, Column, Integer, String, Float, Table, MetaData

# Create an engine to the SQLite database (or another DB of your choice)
engine = create_engine('sqlite:///final_data.db', echo=True)

# Define the table schema using SQLAlchemy's MetaData
metadata = MetaData()
orders = Table('orders', metadata,
    Column('order_id', Integer, primary_key=True),
    Column('product_id', Integer),
    Column('amount', Float),
    Column('status', String)
)

# Create the table
metadata.create_all(engine)

2024-07-25 13:23:09,064 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-07-25 13:23:09,068 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("orders")

2024-07-25 13:23:09,073 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:09,076 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA temp.table_info("orders")

2024-07-25 13:23:09,079 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:09,083 INFO sqlalchemy.engine.Engine
CREATE TABLE orders (
	order_id INTEGER NOT NULL,
	product_id INTEGER,
	amount FLOAT,
	status VARCHAR,
	PRIMARY KEY (order_id)
)

INFO:sqlalchemy.engine.Engine:
CREATE TABLE orders (
	order_id INTEGER NOT NULL,
	product_id INTEGER,
	amount FLOAT,
	status VARCHAR,
	PRIMARY KEY (order_id)
)

2024-07-25 13:23:09,086 INFO sqlalchemy.engine.Engine [no key 0.00324s] ()

INFO:sqlalchemy.engine.Engine:[no key 0.00324s] ()

2024-07-25 13:23:09,105 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

In [24]:
# Load the data into the 'orders' table
df.to_sql('orders', con=engine, if_exists='replace', index=False)

2024-07-25 13:23:43,751 INFO sqlalchemy.engine.Engine BEGIN (implicit)

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)

2024-07-25 13:23:43,776 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("orders")

2024-07-25 13:23:43,780 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,786 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA main.table_info("orders")

2024-07-25 13:23:43,790 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,793 INFO sqlalchemy.engine.Engine SELECT name FROM sqlite_master WHERE type='table' ORDER BY name

INFO:sqlalchemy.engine.Engine:SELECT name FROM sqlite_master WHERE type='table' ORDER BY name

2024-07-25 13:23:43,798 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,801 INFO sqlalchemy.engine.Engine PRAGMA main.table_xinfo("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA main.table_xinfo("orders")

2024-07-25 13:23:43,804 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,808 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'

INFO:sqlalchemy.engine.Engine:SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'

2024-07-25 13:23:43,810 INFO sqlalchemy.engine.Engine [raw sql] ('orders',)

INFO:sqlalchemy.engine.Engine:[raw sql] ('orders',)

2024-07-25 13:23:43,814 INFO sqlalchemy.engine.Engine PRAGMA main.foreign_key_list("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA main.foreign_key_list("orders")

2024-07-25 13:23:43,816 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,819 INFO sqlalchemy.engine.Engine PRAGMA temp.foreign_key_list("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA temp.foreign_key_list("orders")

2024-07-25 13:23:43,822 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,825 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'

INFO:sqlalchemy.engine.Engine:SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'

2024-07-25 13:23:43,828 INFO sqlalchemy.engine.Engine [raw sql] ('orders',)

INFO:sqlalchemy.engine.Engine:[raw sql] ('orders',)

2024-07-25 13:23:43,834 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA main.index_list("orders")

2024-07-25 13:23:43,837 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,839 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA temp.index_list("orders")

2024-07-25 13:23:43,841 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,844 INFO sqlalchemy.engine.Engine PRAGMA main.index_list("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA main.index_list("orders")

2024-07-25 13:23:43,846 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,849 INFO sqlalchemy.engine.Engine PRAGMA temp.index_list("orders")

INFO:sqlalchemy.engine.Engine:PRAGMA temp.index_list("orders")

2024-07-25 13:23:43,852 INFO sqlalchemy.engine.Engine [raw sql] ()

INFO:sqlalchemy.engine.Engine:[raw sql] ()

2024-07-25 13:23:43,855 INFO sqlalchemy.engine.Engine SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'

INFO:sqlalchemy.engine.Engine:SELECT sql FROM  (SELECT * FROM sqlite_master UNION ALL   SELECT * FROM sqlite_temp_master) WHERE name = ? AND type = 'table'

2024-07-25 13:23:43,858 INFO sqlalchemy.engine.Engine [raw sql] ('orders',)

INFO:sqlalchemy.engine.Engine:[raw sql] ('orders',)

2024-07-25 13:23:43,866 INFO sqlalchemy.engine.Engine
DROP TABLE orders

INFO:sqlalchemy.engine.Engine:
DROP TABLE orders

2024-07-25 13:23:43,869 INFO sqlalchemy.engine.Engine [no key 0.00268s] ()

INFO:sqlalchemy.engine.Engine:[no key 0.00268s] ()

2024-07-25 13:23:43,887 INFO sqlalchemy.engine.Engine
CREATE TABLE orders (
	item_id TEXT,
	order_id BIGINT,
	product_id BIGINT,
	amount FLOAT,
	status TEXT,
	item_timestamp TEXT,
	location TEXT,
	customer_name TEXT,
	customer_phone TEXT,
	country TEXT,
	description TEXT
)

INFO:sqlalchemy.engine.Engine:
CREATE TABLE orders (
	item_id TEXT,
	order_id BIGINT,
	product_id BIGINT,
	amount FLOAT,
	status TEXT,
	item_timestamp TEXT,
	location TEXT,
	customer_name TEXT,
	customer_phone TEXT,
	country TEXT,
	description TEXT
)

2024-07-25 13:23:43,892 INFO sqlalchemy.engine.Engine [no key 0.00503s] ()

INFO:sqlalchemy.engine.Engine:[no key 0.00503s] ()

2024-07-25 13:23:45,281 INFO sqlalchemy.engine.Engine INSERT INTO orders (item_id, order_id, product_id, amount, status, item_timestamp, location, customer_name, customer_phone, country, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

INFO:sqlalchemy.engine.Engine:INSERT INTO orders (item_id, order_id, product_id, amount, status, item_timestamp, location, customer_name, customer_phone, country, description) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

2024-07-25 13:23:45,286 INFO sqlalchemy.engine.Engine [generated in 0.88163s] (('4dc01ae9-c1a8-461e-afa5-7e426578fd0a', 160794, 647, 1500.0, 'Cancelled', '2024-01-13 21:34:34.618927', 'East Cameron', 'Richard Stevens', '(774)709-6342x106', 'Guatemala', 'Room as address heart vote PM.'), ('77944e0c-f500-456a-9f18-32f2948e93d3', 510841, 243, 848.88, 'Cancelled', '2024-05-29 17:05:37.436639', 'South Christinaburgh', 'Patrick Allen', '001-734-642-3018', 'Mauritania', 'Accept part crime hot leave.'), ('1019711d-53c9-4015-bb0b-c3b23149dfa2', 259964, 209, 614.64, 'Returned', '2024-01-03 02:18:15.231398', 'South Jeremybury', 'Wendy White', '+1-210-390-0363', 'Cameroon', 'Top huge old behavior western. Huge according fight until. Magazine meet similar director least.'), ('50020fa6-e77e-4cea-b133-df6c55d5fa60', 951786, 316, 1500.0, 'Shipped', '2024-05-08 17:57:57.333306', 'Jessicabury', 'Lisa Bradley', '+1-203-409-1537x25704', 'Egypt', 'Truth responsibility wish send. Part father never benefit. Many short cover forward.'), ('bb6e3160-6de1-462f-aec6-2494e7e2d370', 524028, 8, 424.56, 'Returned', '2024-02-10 19:46:11.271562', 'Melissafurt', 'Victor Taylor', '+1-815-967-7476x1122', 'Norfolk Island', 'Business investment city Democrat. Every leave several cultural. Finish join though hair.'), ('af637d83-158f-43c3-8736-7273f444aff5', 17471, 195, 1500.0, 'Pending', '2024-04-21 11:41:41.783081', 'Pearsonfort', 'Adam Rodriguez PhD', '260-869-2672', 'Christmas Island', 'Class east machine skill tax trip. Model song us.'), ('c22ba24d-4a25-44b0-ba91-26af5d7457a2', 577128, 752, 161.24, 'Pending', '2024-03-04 18:05:49.397663', 'Port Alicia', 'Randy Hernandez', '657.683.0611x2258', 'Morocco', 'Next along Republican something piece policy anything blue. Note kitchen respond important.'), ('7f4dca60-5245-49d8-86eb-9e0dcd69300a', 915, 773, 260.92, 'Returned', '2024-06-16 21:16:40.141470', 'Haasview', 'Ryan Flowers', '767-539-0086x59382', 'Jersey', 'Question set miss whether. Vote environmental several as middle.')  ... displaying 10 of 83401 total bound parameter sets ...  ('7585fdbe-4f41-4fbd-8853-ccd66a63d1f9', 673119, 484, 1500.0, 'Shipped', '2024-03-15 12:55:52.131511', 'Port Shane', 'Alexis Kennedy', '(809)766-9356', 'Colombia', 'Fact relationship exist message life. Line sport provide budget.'), ('2d8e67d2-0d5d-49c5-b10f-5e48bcaf64ca', 237918, 223, 1500.0, 'Cancelled', '2024-01-24 16:40:23.514176', 'Mckinneyberg', 'Thomas Palmer', '321-258-5265x7061', 'Pakistan', 'If option weight thus participant appear coach great. Who others door week.'))

INFO:sqlalchemy.engine.Engine:[generated in 0.88163s] (('4dc01ae9-c1a8-461e-afa5-7e426578fd0a', 160794, 647, 1500.0, 'Cancelled', '2024-01-13 21:34:34.618927', 'East Cameron', 'Richard Stevens', '(774)709-6342x106', 'Guatemala', 'Room as address heart vote PM.'), ('77944e0c-f500-456a-9f18-32f2948e93d3', 510841, 243, 848.88, 'Cancelled', '2024-05-29 17:05:37.436639', 'South Christinaburgh', 'Patrick Allen', '001-734-642-3018', 'Mauritania', 'Accept part crime hot leave.'), ('1019711d-53c9-4015-bb0b-c3b23149dfa2', 259964, 209, 614.64, 'Returned', '2024-01-03 02:18:15.231398', 'South Jeremybury', 'Wendy White', '+1-210-390-0363', 'Cameroon', 'Top huge old behavior western. Huge according fight until. Magazine meet similar director least.'), ('50020fa6-e77e-4cea-b133-df6c55d5fa60', 951786, 316, 1500.0, 'Shipped', '2024-05-08 17:57:57.333306', 'Jessicabury', 'Lisa Bradley', '+1-203-409-1537x25704', 'Egypt', 'Truth responsibility wish send. Part father never benefit. Many short cover forward.'), ('bb6e3160-6de1-462f-aec6-2494e7e2d370', 524028, 8, 424.56, 'Returned', '2024-02-10 19:46:11.271562', 'Melissafurt', 'Victor Taylor', '+1-815-967-7476x1122', 'Norfolk Island', 'Business investment city Democrat. Every leave several cultural. Finish join though hair.'), ('af637d83-158f-43c3-8736-7273f444aff5', 17471, 195, 1500.0, 'Pending', '2024-04-21 11:41:41.783081', 'Pearsonfort', 'Adam Rodriguez PhD', '260-869-2672', 'Christmas Island', 'Class east machine skill tax trip. Model song us.'), ('c22ba24d-4a25-44b0-ba91-26af5d7457a2', 577128, 752, 161.24, 'Pending', '2024-03-04 18:05:49.397663', 'Port Alicia', 'Randy Hernandez', '657.683.0611x2258', 'Morocco', 'Next along Republican something piece policy anything blue. Note kitchen respond important.'), ('7f4dca60-5245-49d8-86eb-9e0dcd69300a', 915, 773, 260.92, 'Returned', '2024-06-16 21:16:40.141470', 'Haasview', 'Ryan Flowers', '767-539-0086x59382', 'Jersey', 'Question set miss whether. Vote environmental several as middle.')  ... displaying 10 of 83401 total bound parameter sets ...  ('7585fdbe-4f41-4fbd-8853-ccd66a63d1f9', 673119, 484, 1500.0, 'Shipped', '2024-03-15 12:55:52.131511', 'Port Shane', 'Alexis Kennedy', '(809)766-9356', 'Colombia', 'Fact relationship exist message life. Line sport provide budget.'), ('2d8e67d2-0d5d-49c5-b10f-5e48bcaf64ca', 237918, 223, 1500.0, 'Cancelled', '2024-01-24 16:40:23.514176', 'Mckinneyberg', 'Thomas Palmer', '321-258-5265x7061', 'Pakistan', 'If option weight thus participant appear coach great. Who others door week.'))

2024-07-25 13:23:45,707 INFO sqlalchemy.engine.Engine COMMIT

INFO:sqlalchemy.engine.Engine:COMMIT

83401